dist: bionic

language: go
#go_import_path: tobw

go:
  - 1.12.x
  - 1.13.x

before_install:
  - make bootstrap

install:
  - make dep

before_script:
  - make vet
  - make check_spelling

script:
  - make



