
# network listener configuration
network:
  listener:
    - type: "tcp"
      port: 5050
      unicode_convert: false
      address: "0.0.0.0"
    - type: "ssh"
      port: 5022
      unicode_convert: true
      address: "0.0.0.0"
    - type: "telnet"
      port: 5023
      unicode_convert: true
      address: "0.0.0.0"

# Postgres database config

database:
  host: "localhost"
  database: "tobw"
  user: "tobw"
  password: "tobw"
  port: 5432