database:
  host: "localhost"
  name: "tobw"
  user: "tobw"
  password: "tobw"
  port: 5432

options:
  logLevel: "info"
  #location of ssh host key to use. Either full path, or relative path from current work directory.
  sshPrivateKey: "security/tobw_rsa"

prometheus:
  enabled: true

listeners:
  - address: "0.0.0.0"
    port: 5000
    protocol: "raw"
    convertUTF8: true
  - address: "0.0.0.0"
    port: 5022
    protocol: "ssh"
    convertUTF8: true
  - address: "0.0.0.0"
    port: 5023
    protocol: "telnet"
    convertUTF8: true
  - address: "0.0.0.0"
    port: 6000
    protocol: "raw"
    convertUTF8: false
